### ISSUE TITLE
Cannot install 9014 on Linksys E2500v1

### ISSUE THREAD

**Issue by Commod0re** [Victek/Tomato-RAF#14]
Hello!

I have been having some issues with an E2500v1 that is currently running Tomato RAF Firmware v1.28.9013 MIPSR2-RAF-V1.2x K26 USB. It's configured in wireless client mode, acting as a wireless ethernet bridge for two devices. However, it has been rebooting periodically for no apparent reason, so I attempted to install `tomato-E2500v3USB-NVRAM60K-1.28.9014MIPSR2-RAF-v1.3g.bin` because I saw no download specifically for the E2500v1. After the binary uploads, though, I get the error message "File contains an invalid header" and the upgrade does not proceed.

Do I need to build from source for this device, maybe?

**Comment by Commod0re** [comment]
Yep, that was it. Built an image with `make V1=9014 V2=RAF e2500` and it installed no problem.

**Comment by Victek** [comment]
Great.. Thx!
