### ISSUE TITLE
QOS Inbound Graph broken

### ISSUE THREAD

**Issue by izenn** [Victek/Tomato-RAF#3]
Nothing is being registered by the inbound QOS classifier/grapher (see attached image)
![screen shot 2014-03-04 at 10 09 16 am](https://f.cloud.github.com/assets/744288/2322991/6e5563c0-a3b7-11e3-9f61-1b33798b249e.png)

**Comment by izenn** [comment]
Here is the realtime bandwidth graph that shows that there is inbound traffic:
![screen shot 2014-03-04 at 10 20 34 am](https://f.cloud.github.com/assets/744288/2323110/003c79da-a3b9-11e3-8662-03ac8be37b14.png)

**Comment by Victek** [comment]
Did you enabled the function?

![screenshot from 2014-03-04 17 42 18](https://f.cloud.github.com/assets/915948/2323534/e3e4f816-a3bd-11e3-9d1f-fe25dae83310.png)

and then you will see it...

![screenshot from 2014-03-04 17 41 06](https://f.cloud.github.com/assets/915948/2323546/f788db3a-a3bd-11e3-9580-ffad8aa462c7.png)

If not, clear nvram and configure again.

**Comment by izenn** [comment]
settings are enabled, i'll clear nvram and re-configure now

/edit:
the nvram reset fixed it.  Thanks!
